require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Max: 200

Rails/I18nLocaleTexts:
  Enabled: false

Rails/FilePath:
  Enabled: false

convention:Metrics/BlockLength:
  Max: 170

RSpec/MultipleExpectations:
  Max: 100

RSpec/ExampleLength:
  Max: 100

RSpec/FilePath:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false
