:schedule:
  forecast_job:
    cron: '0 */3 * * * Europe/Moscow'
    class: ForecastJob
    queue: default
  check_fill_bd_job:
    cron: '* * * * * Europe/Moscow'
    class: CheckFillBdJob
    queue: default
